config/routes.rb
Rails.application.routes.draw do
  resources :newsfeeds

  resources :unit_instances do
    member do
      get 'cancel_build'
      get 'instant_build'
      get 'build'
    end
  end

  resources :units
  resources :build_lists

  resources :facility_instances do
    member do
      get 'build'
      get 'cancel_build'
      get 'instant_build'
    end
  end

  resources :expedition_instances

  get 'notification_view/index'
  resources :damage_types
  resources :fighting_fleets do
    resources :ship_groups
    resources :fights
    member do
      get 'callback'
    end
  end

  resources :fights
  resources :science_instances do
    member do
      get 'research'
      get 'cancel_research'
      get 'instant_research'
    end
  end

  resources :ships do
    member do
      get 'cheat'
    end
    resources :ships_stations
  end

  resources :ships_stations do
    member do
      get 'upgrade'
      get 'cancel_upgrade'
      get 'instant_upgrade'
      get 'downgrade'
    end
  end

  resources :user_ships
  resources :notifications
  resources :messages
  resources :stations
  resources :sciences
  resources :facilities
  resources :expeditions
  resources :science
  resources :ranks
  resources :user_icons
  resources :ships
  resources :ships_station

  resources :trades do
    member do
      get 'buy'
    end
  end

  get 'home/index'
  get 'home/get_json_data', defaults: {format: 'json'}
  get 'profile/index'
  get 'profile/user'
  get 'profile/:username', to: 'profile#user', as: 'profile'
  get 'home/index'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'newsfeeds#index'
    end
    unauthenticated :user do
      root :to => 'newsfeeds#index', as: :unauthenticated_root
    end
  end

end

app/models/build_list.rb
class BuildList < ActiveRecord::Base
	belongs_to :ship

after_create :startBuild

def startBuild
	case self.typeSign

	when 'f'
		if ship.build_list_count(self.typeSign) <= 1
			facility_instance = FacilityInstance.find_by(id: self.instance_id)
    		facility_instance.start_time = Time.now
			facility_instance.save	
		end
	when 'u'
		if ship.build_list_count(self.typeSign) <= 1
			unit_instance = UnitInstance.find_by(id: self.instance_id)
    		unit_instance.start_time = Time.now
			unit_instance.save	
		end
	when 'r'
		science_instance = ScienceInstance.find_by(id: self.instance_id)
		science_instance.research_ship = ship.id
    	science_instance.start_time = Time.now
		science_instance.save	
	when 's'
		station_instance = ShipsStation.find_by(id: self.instance_id)
    	station_instance.start_time = Time.now
		station_instance.save	
	when 'n'	
	end
end

def getDuration
	case self.typeSign
	when 'f'
		return getDurationF
	when 'u'
		return getDurationU
	when 'r'
		return getDurationR
	when 's'
		return getDurationS
	when 'n'
		return 0
	end
end

def getDurationF(instance = FacilityInstance.find_by(id: self.instance_id))
	return Facility.update_time(instance, false)
end

def getDurationS(instance = ShipsStation.find_by(id: self.instance_id))
	return Station.update_time(instance, false)
end

def getDurationR(instance = ScienceInstance.find_by(id: self.instance_id))
	return Science.update_time(instance, false)
end

def getDurationU(instance = UnitInstance.find_by(id: self.instance_id))
	return Unit.update_time(instance, false)
end

end

app/controllers/build_lists_controller.rb
class BuildListsController < ApplicationController
  before_action :set_build_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /build_lists
  # GET /build_lists.json
  def index
    if current_user.activeShip == nil 
      redirect_to :controller => 'ships', :action => 'new'
      return
    end
    @build_lists = BuildList.all
  end

  # GET /build_lists/1
  # GET /build_lists/1.json
  def show
  end

  # GET /build_lists/new
  def new
    @build_list = BuildList.new
  end

  # GET /build_lists/1/edit
  def edit
  end

  # POST /build_lists
  # POST /build_lists.json
  def create
    @build_list = BuildList.new(build_list_params)

    respond_to do |format|
      if @build_list.save
        format.html { redirect_to @build_list, notice: 'Build list was successfully created.' }
        format.json { render :show, status: :created, location: @build_list }
      else
        format.html { render :new }
        format.json { render json: @build_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /build_lists/1
  # PATCH/PUT /build_lists/1.json
  def update
    respond_to do |format|
      if @build_list.update(build_list_params)
        format.html { redirect_to @build_list, notice: 'Build list was successfully updated.' }
        format.json { render :show, status: :ok, location: @build_list }
      else
        format.html { render :edit }
        format.json { render json: @build_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /build_lists/1
  # DELETE /build_lists/1.json
  def destroy
    @build_list.destroy
    respond_to do |format|
      format.html { redirect_to build_lists_url, notice: 'Build list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build_list
      @build_list = BuildList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_list_params
      params.require(:build_list).permit(:typeSign, :instance_id)
    end
end

app/helpers/build_lists_helper.rb
module BuildListsHelper
end

app/views/build_lists/_form.html.erb
<%= form_for(@build_list) do |f| %>
  <% if @build_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build_list.errors.count, "error") %> prohibited this build_list from being saved:</h2>

      <ul>
      <% @build_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :typeSign %><br>
    <%= f.text_field :typeSign %>
  </div>
  <div class="field">
    <%= f.label :instance_id %><br>
    <%= f.number_field :instance_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/build_lists/edit.html.erb
<h1>Editing Build List</h1>

<%= render 'form' %>

<%= link_to 'Show', @build_list %> |
<%= link_to 'Back', build_lists_path %>

app/views/build_lists/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert" style='color:red'><%= alert %></p>

<h1 class="userlabel">Management</h1>

<table id="table_energy">
  <thead>
    <tr>
      <th>Metall Scanner</th>
      <th>Kristall Scanner</th>
      <th>Treibstoff Scanner</th>
      <th>Verbrennungsgenerator</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.active_ship.get_energy%>
    <% current_user.active_ship.get_used_energy%>
    <% metal_scan = current_user.active_ship.ships_stations.find_by(station_id: 2001) %>
    <% crystal_scan = current_user.active_ship.ships_stations.find_by(station_id: 2002) %>
    <% fuel_scan = current_user.active_ship.ships_stations.find_by(station_id: 2003) %>
    <% burner = current_user.active_ship.ships_stations.find_by(station_id: 2015) %>

    <tr>
      <% station = metal_scan.station %>
      <td>
        <a>
            <img src= "<%= image_url("stations/" + metal_scan.station.icon)%>", width="50", height="50", id="icon">
            <span><%= Message.find_by_code(station.id).mes %></span>
        </a>
      </td>
      <% station = crystal_scan.station %>
      <td>
        <a>
            <img src= "<%= image_url("stations/" + crystal_scan.station.icon)%>", width="50", height="50", id="icon">
            <span><%= Message.find_by_code(station.id).mes %></span>
        </a>
      </td>
      <% station = fuel_scan.station %>
      <td>
        <a>
            <img src= "<%= image_url("stations/" + fuel_scan.station.icon)%>", width="50", height="50", id="icon">
            <span><%= Message.find_by_code(station.id).mes %></span>
        </a>
      </td>
      <% station = burner.station %>
      <td>
        <a>
            <img src= "<%= image_url("stations/" + burner.station.icon)%>", width="50", height="50", id="icon">
            <span><%= Message.find_by_code(station.id).mes %></span>
        </a>
      </td>
    </tr>

    <tr>
      <td>
        <p class="note"><%= metal_scan.energy_usage %>%</p>
      </td>
      <td>
        <p class="note"><%= crystal_scan.energy_usage %>%</p>
      </td>
      <td>
        <p class="note"><%= fuel_scan.energy_usage %>%</p>
      </td>
      <td>
        <p class="note"><%= burner.energy_usage %>%</p>
      </td>
    </tr>

    <tr>
      <td>
        <%= form_for metal_scan do |f| %>
          <%= f.range_field :energy_usage, class:'slider_format' %>
          <br>
          <%= f.submit 'Aktualisieren', class: 'button_formater' %>
        <% end %>
      </td>
      <td>
        <%= form_for crystal_scan do |f| %>
          <%= f.range_field :energy_usage, class:'slider_format' %>
          <br>
          <%= f.submit 'Aktualisieren', class: 'button_formater' %>
        <% end %>
      </td>

      <td>
        <%= form_for fuel_scan do |f| %>
          <%= f.range_field :energy_usage, class:'slider_format' %>
          <br>
          <%= f.submit 'Aktualisieren', class: 'button_formater' %>
        <% end %>
      </td>

      <td>
        <%= form_for burner do |f| %>
          <%= f.range_field :energy_usage, class:'slider_format' %>
          <br>
          <%= f.submit 'Aktualisieren', class: 'button_formater' %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<br>
<br>
<table  id="table_builds">
  <thead>
    <% if @build_lists.count != 0 %>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Dauer</th>
      <th>Abbruch</th>
      <th>Premium Funktion</th>
      <th>Auftragsschiff</th>
      <th>Aktueller Status</th>
      <th>In Auftrag</th>
      <th colspan="3"></th>
    </tr>
    <% end %>
  </thead>

  <tbody>
    <% @build_lists.sort_by{|instance| (instance.getDuration)}.each do |build_list| %>
      <% if(build_list.ship.user_ship.user == current_user) %>
        <% found = false %>
        <% ship = current_user.ships.find(current_user.activeShip) %>

        <% if build_list.typeSign == 'f' %>
          <% instance = FacilityInstance.find_by(id: build_list.instance_id) %>
          <% if instance != nil %>
            <% main = instance.facility %>
            <% mesId = main.facility_condition_id+3000 %>
            <% iconPath = "facility_icons/" + main.icon %>
            <% class_main = Facility %>
            <% found = true %>
            <% inactive = nil %>
            <% if(!ship.is_building(instance)) %>
              <tr id="inactive">
              <% inactive = true %>
            <% else %>
              <tr id="active">
              <% inactive = false %>
            <% end %>
          <% end %>
        <% end %>


        <% if build_list.typeSign == 'u' %>
          <% instance = UnitInstance.find_by(id: build_list.instance_id) %>
          <% if instance != nil %>
            <% main = instance.unit %>
            <% mesId = main.message.code %>
            <% iconPath = main.icon %>
            <% class_main = Unit %>
            <% found = true %>
            <% inactive = nil %>
            <% if(!ship.is_building(instance)) %>
              <tr id="inactive">
              <% inactive = true %>
            <% else %>
              <tr id="active">
              <% inactive = false %>
            <% end %>
          <% end %>
        <% end %>

        <% if build_list.typeSign == 'r' %>
          <% instance = ScienceInstance.find_by(id: build_list.instance_id) %>
          <% if instance != nil %>
            <% main = instance.science %>
            <% mesId = main.id %>
            <% iconPath = "science_icons/" + main.icon %>
            <% class_main = Science %>
            <% found = true %>
            <% inactive = nil %>
            <% if(!current_user.is_elsewhere_researching(instance)) %>
              <tr id="inactive">
              <% inactive = true %>
            <% else %>
              <tr id="active">
              <% inactive = false %>
            <% end %>
          <% end %>
        <% end %>

        <% if build_list.typeSign == 's' %>
          <% instance = ShipsStation.find_by(id: build_list.instance_id) %>
          <% if instance != nil %>
            <% main = instance.station %>
            <% mesId = main.id %>
            <% iconPath = "stations/" + main.icon %>
            <% class_main = Station %>
            <% found = true %>
            <% inactive = nil %>
            <% if(!ship.is_upgrading(instance)) %>
              <tr id="inactive">
              <% inactive = true %>
            <% else %>
              <tr id="active">
              <% inactive = false %>
            <% end %>
          <% end %>
        <% end %>


        <% if found %>



          <% mes = Message.find_by_code(mesId).mes %>
          <td>
            <a>
              <img src= "<%= image_url(iconPath)%>", width="50", height="50", id="icon">
              <span><%= mes %></span>
            </a>
          </td>
          <td>
              <%= main.name %>
          </td>
          <% if(inactive) %>
            <td id = "not_running"><%= class_main.update_time(instance, true).to_s %></td>
          <% else %>
            <td class="running"
              data-id="<%= main.id %>"
              data-time="<%= build_list.getDuration.to_s %>">
            </td>
          <%end %>


          <% if build_list.typeSign == 'f' %>
            <td><%= button_to 'Abbrechen', cancel_build_facility_instance_path(instance), method: :get %>
            <td><%= button_to 'Sofort', instant_build_facility_instance_path(instance), method: :get %></td>
            <td><%= instance.ship.name %></td>
            <td><%= instance.count %></td>
            <td><%= instance.create_count || 0 %></td>
          <% end %>

          <% if build_list.typeSign == 'u' %>
            <td><%= button_to 'Abbrechen', cancel_build_unit_instance_path(instance), method: :get %>
            <td><%= button_to 'Sofort', instant_build_unit_instance_path(instance), method: :get %></td>
            <td><%= instance.ship.name %></td>
            <td><%= instance.amount %></td>
            <td><%= instance.build_amount || 0 %></td>
          <% end %>

          <% if build_list.typeSign == 'r' %>
            <td>
              <a>
                <%= button_to 'Abbrechen', cancel_research_science_instance_path(instance), method: :get %>
                <span><%= instance.get_refund %></span>
              </a>
            </td>
            <td>
              <%= button_to 'Sofort', instant_research_science_instance_path(instance), method: :get %>
            </td>
            <td><%= Ship.find_by(id: instance.research_ship).name %></td>
            <td><%= instance.level %></td>
            <td><%= instance.level + 1 %></td>
          <% end %>

          <% if build_list.typeSign == 's' %>
            <td>
              <a>
                <%= button_to 'Abbrechen', cancel_upgrade_ships_station_path(instance), method: :get %>
                <span><%= instance.get_refund %></span>
              </a>
            </td>
            <td>
              <%= button_to 'Sofort', instant_upgrade_ships_station_path(instance), method: :get %>
            </td>
            <td><%= instance.ship.name %></td>
            <td><%= instance.level %></td>
            <td><%= instance.level + 1 %></td>
          <% end %>

          <% if current_user.is_admin %>
            <td><%= link_to 'Show', build_list %></td>
            <td><%= link_to 'Edit', edit_build_list_path(build_list) %></td>
            <td><%= link_to 'Destroy', build_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% else %>
          <% if current_user.is_admin %>
            <td>Damaged Build:&nbsp; </td>
            <td><%= link_to 'Destroy', build_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= javascript_tag "start_timer()" -%>

app/views/build_lists/new.html.erb
<h1>New Build List</h1>

<%= render 'form' %>

<%= link_to 'Back', build_lists_path %>

app/views/build_lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_build_list_path(@build_list) %> |
<%= link_to 'Back', build_lists_path %>