config/routes.rb
Rails.application.routes.draw do
  resources :newsfeeds

  resources :unit_instances do
    member do
      get 'cancel_build'
      get 'instant_build'
      get 'build'
    end
  end

  resources :units
  resources :build_lists

  resources :facility_instances do
    member do
      get 'build'
      get 'cancel_build'
      get 'instant_build'
    end
  end

  resources :expedition_instances

  get 'notification_view/index'
  resources :damage_types
  resources :fighting_fleets do
    resources :ship_groups
    resources :fights
    member do
      get 'callback'
    end
  end

  resources :fights
  resources :science_instances do
    member do
      get 'research'
      get 'cancel_research'
      get 'instant_research'
    end
  end

  resources :ships do
    member do
      get 'cheat'
    end
    resources :ships_stations
  end

  resources :ships_stations do
    member do
      get 'upgrade'
      get 'cancel_upgrade'
      get 'instant_upgrade'
      get 'downgrade'
    end
  end

  resources :user_ships
  resources :notifications
  resources :messages
  resources :stations
  resources :sciences
  resources :facilities
  resources :expeditions
  resources :science
  resources :ranks
  resources :user_icons
  resources :ships
  resources :ships_station

  resources :trades do
    member do
      get 'buy'
    end
  end

  get 'home/index'
  get 'home/get_json_data', defaults: {format: 'json'}
  get 'profile/index'
  get 'profile/user'
  get 'profile/:username', to: 'profile#user', as: 'profile'
  get 'home/index'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'newsfeeds#index'
    end
    unauthenticated :user do
      root :to => 'newsfeeds#index', as: :unauthenticated_root
    end
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    redirect_to notification_view_index_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :message_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.text_field :message_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1  class="userlabel">Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user.username %></td>
        <td><%= notification.message.mes %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>