config/routes.rb
Rails.application.routes.draw do
  resources :newsfeeds

  resources :unit_instances do
    member do
      get 'cancel_build'
      get 'instant_build'
      get 'build'
    end
  end

  resources :units
  resources :build_lists

  resources :facility_instances do
    member do
      get 'build'
      get 'cancel_build'
      get 'instant_build'
    end
  end

  resources :expedition_instances

  get 'notification_view/index'
  resources :damage_types
  resources :fighting_fleets do
    resources :ship_groups
    resources :fights
    member do
      get 'callback'
    end
  end

  resources :fights
  resources :science_instances do
    member do
      get 'research'
      get 'cancel_research'
      get 'instant_research'
    end
  end

  resources :ships do
    member do
      get 'cheat'
    end
    resources :ships_stations
  end

  resources :ships_stations do
    member do
      get 'upgrade'
      get 'cancel_upgrade'
      get 'instant_upgrade'
      get 'downgrade'
    end
  end

  resources :user_ships
  resources :notifications
  resources :messages
  resources :stations
  resources :sciences
  resources :facilities
  resources :expeditions
  resources :science
  resources :ranks
  resources :user_icons
  resources :ships
  resources :ships_station

  resources :trades do
    member do
      get 'buy'
    end
  end

  get 'home/index'
  get 'home/get_json_data', defaults: {format: 'json'}
  get 'profile/index'
  get 'profile/user'
  get 'profile/:username', to: 'profile#user', as: 'profile'
  get 'home/index'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'newsfeeds#index'
    end
    unauthenticated :user do
      root :to => 'newsfeeds#index', as: :unauthenticated_root
    end
  end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :damage_type
  belongs_to :message
  belongs_to :science_one, :class_name => 'Science', :foreign_key => 'science_one_id'
  belongs_to :science_two, :class_name => 'Science', :foreign_key => 'science_two_id'
  has_many :unit_instances, dependent: :destroy
  has_many :ships, :through => :unit_instances
  validates_presence_of :metal_price, :crystal_price, :fuel_price, :name, :condition_id, :icon, :shell, :damage, :damage_type_id, :cargo, :speed

  def get_total_cost
    return self.get_fuel_cost * 4 + self.get_crystal_cost * 2 + self.get_metal_cost
  end

  def get_metal_cost
  	return self.metal_price * 500
  end

  def get_crystal_cost
  	return self.crystal_price * 500
  end

  def get_fuel_cost
  	return self.fuel_price * 500
  end

  def get_metal_cost_ratio(ratio)
    return self.get_metal_cost * ratio
  end

  def get_crystal_cost_ratio(ratio)
    return self.get_crystal_cost * ratio
  end

  def get_fuel_cost_ratio(ratio)
    return self.get_fuel_cost * ratio
  end

   def self.update_time(instance, format)
    durationInSeconds = instance.get_duration()
    if(instance.start_time != nil)
      timeSinceResearch = (Time.now - instance.start_time).to_i
      restTime = durationInSeconds - timeSinceResearch

      if(restTime <= 0)
        instance.build_amount -= 1 
        instance.amount += 1
        instance.start_time = Time.now
        instance.save
        if(instance.build_amount <= 0)
          instance.reset_build
        end

        if not(format)
          return durationInSeconds;
        else
          return format_count_time(durationInSeconds)
        end
      else
        if not(format)
          return restTime;
        else
          return format_count_time(restTime)
        end
      end
    else
      if not(format)
        return durationInSeconds;
      else
        return format_count_time(durationInSeconds)
      end
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :build, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    if current_user.activeShip == nil 
      redirect_to :controller => 'ships', :action => 'new'
      return
    end
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

#  def build
#    ship = Ship.find_by(:id => params[:ship_id])
#    instance = ship.get_unit_instance(Unit.find_by(:id => params[:unit_id]))
#    unit = instance.unit
#
#    if not (params[:amount].nil? || params[:amount] == 0)
#      amount = params[:amount].to_i
#
#      metal = unit.get_metal_cost()* amount
#      crystal = unit.get_crystal_cost() * amount
#      fuel = unit.get_fuel_cost() * amount
#      current_user.remove_resources_from_current_ship(metal, crystal, fuel)
#
#      if(instance.start_time.nil?)
#        instance.start_time = Time.now
#        instance.build_amount = params[:amount].to_i
#      else
#        instance.build_amount = params[:amount].to_i + instance.build_amount
#      end
#
#      instance.save
#    end
#    redirect_to units_url
#  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:condition_id, :name, :metal_price, :crystal_price, :fuel_price, :shell, :damage, :damage_type_id, :cargo, :speed)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :metal_price %><br>
    <%= f.number_field :metal_price %>
  </div>
  <div class="field">
    <%= f.label :crystal_price %><br>
    <%= f.number_field :crystal_price %>
  </div>
  <div class="field">
    <%= f.label :fuel_price %><br>
    <%= f.number_field :fuel_price %>
  </div>
  <div class="field">
    <%= f.label :shell %><br>
    <%= f.number_field :shell %>
  </div>
  <div class="field">
    <%= f.label :damage %><br>
    <%= f.number_field :damage %>
  </div>
  <div class="field">
    <%= f.label :damage_type_id %><br>
    <%= f.text_field :damage_type_id %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.number_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.number_field :speed %>
  </div>
  <div class="field">
    <%= f.label :condition_id %><br>
    <%= f.number_field :condition_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert" style='color:red'><%= alert %></p>

<h1 class="userlabel">Einheiten</h1>
<%= button_to 'UnitCheat', unit_instances_path, method: :get %>
<table id="table_units">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Metall</th>
      <th>Kristall</th>
      <th>Treibstoff</th>
      <th>Dauer</th>
      <th>Anzahl</th>
      <th>In Auftrag</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @units.sort_by{|u| u.condition_id}.each do |unit| %>
      <% ship = current_user.active_ship %>
      <% instance = ship.unit_instances.find_by(:unit_id => unit.id)%>

      <% inactive = nil %>

      <% if(!ship.is_building(instance)) %>
        <tr id="inactive">
          <% inactive = true %>
      <% else %>
        <tr id="active">
          <% inactive = false %>
      <% end %>

      <% if(instance.id) %>
        <td>
          <a>
            <img src= "<%= image_url(unit.icon)%>", width="50", height="50", id="icon">
            <span><%= unit.message.mes %></span>
          </a>
        </td>
        <td><%= unit.name %></td>
        <td><%= unit.get_metal_cost %></td>
        <td><%= unit.get_crystal_cost %></td>
        <td><%= unit.get_fuel_cost %></td>

        <% if(inactive) %>
          <td id = "not_running"><%= Unit.update_time(instance, true).to_s %></td>
        <% else %>
          <td class="running"
            data-id="<%= instance.unit_id %>"
            data-time="<%= Unit.update_time(instance, false) %>">
          </td>
        <% end %>
        <% availability = instance.check_conditions && !ship.capped_units %>
        <td><%= instance.amount %></td>
        <td><%= instance.build_amount || 0 %></td>
        <% if !availability %>
          <td><a>Nicht verfügbar<span><%= instance.get_conditions() %></span>
          </a></td>
        <% else %>
          <td>
            <a>
              <%= form_tag build_unit_instance_path(instance), method: 'get' do %>    
                <%= number_field_tag(:create_amount, nil, placeholder: '0', min: 0, max: instance.get_max_buy_amount()) %>
                <%= submit_tag 'Herstellen', data: { confirm: 'Are you sure?' }, method: :get %>
              <% end %>
              <span><%= 'Maximale Bauanzahl: ' + instance.get_max_buy_amount().to_s.html_safe %></span>
            </a>
          </td>
        <% end %>
        <% if(ship.build_lists.find_by(typeSign: 'u', instance_id: instance.id) != nil) %>
          <td><%= button_to 'Abbrechen', cancel_build_unit_instance_path(instance), method: :get %></td>
          <td><%= button_to 'Sofort', instant_build_unit_instance_path(instance), method: :get %></td>
        <% end %>
      <% end %>
    <% end %>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'New Unit', new_unit_path %>
<%= link_to 'LevelCheat', unit_instances_path %>

<%= javascript_tag "start_timer()" -%>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Metal price:</strong>
  <%= @unit.metal_price %>
</p>

<p>
  <strong>Crystal price:</strong>
  <%= @unit.crystal_price %>
</p>

<p>
  <strong>Fuel price:</strong>
  <%= @unit.fuel_price %>
</p>

<p>
  <strong>Shell:</strong>
  <%= @unit.shell %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @unit.damage %>
</p>

<p>
  <strong>Damage type:</strong>
  <%= @unit.damage_type %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @unit.cargo %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @unit.speed %>
</p>

<p>
  <strong>ConditionID:</strong>
  <%= @unit.condition_id %>
</p>

<p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>