config/routes.rb
Rails.application.routes.draw do
  resources :newsfeeds

  resources :unit_instances do
    member do
      get 'cancel_build'
      get 'instant_build'
      get 'build'
    end
  end

  resources :units
  resources :build_lists

  resources :facility_instances do
    member do
      get 'build'
      get 'cancel_build'
      get 'instant_build'
    end
  end

  resources :expedition_instances

  get 'notification_view/index'
  resources :damage_types
  resources :fighting_fleets do
    resources :ship_groups
    resources :fights
    member do
      get 'callback'
    end
  end

  resources :fights
  resources :science_instances do
    member do
      get 'research'
      get 'cancel_research'
      get 'instant_research'
    end
  end

  resources :ships do
    member do
      get 'cheat'
    end
    resources :ships_stations
  end

  resources :ships_stations do
    member do
      get 'upgrade'
      get 'cancel_upgrade'
      get 'instant_upgrade'
      get 'downgrade'
    end
  end

  resources :user_ships
  resources :notifications
  resources :messages
  resources :stations
  resources :sciences
  resources :facilities
  resources :expeditions
  resources :science
  resources :ranks
  resources :user_icons
  resources :ships
  resources :ships_station

  resources :trades do
    member do
      get 'buy'
    end
  end

  get 'home/index'
  get 'home/get_json_data', defaults: {format: 'json'}
  get 'profile/index'
  get 'profile/user'
  get 'profile/:username', to: 'profile#user', as: 'profile'
  get 'home/index'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'newsfeeds#index'
    end
    unauthenticated :user do
      root :to => 'newsfeeds#index', as: :unauthenticated_root
    end
  end

end

app/models/science.rb
require 'TimeFormatter'

class Science < ActiveRecord::Base
  has_one :science_one, :class_name => 'Unit', :foreign_key => "science_one_id"
  has_one :science_two, :class_name => 'Unit', :foreign_key => "science_two_id"
  has_many :science_instances, dependent: :destroy
  has_many :users, :through => :science_instances
  validates_presence_of :cost1, :cost2, :cost3, :factor, :duration, :name, :tier, :science_condition_id, :icon

  def get_metal_cost(level)
    return (self.cost1 * 500 * self.factor ** (level)).to_i
  end

  def get_metal_cost_ratio(level, ratio)
    return get_metal_cost(level).to_f * ratio
  end

  def get_crystal_cost(level)
    return (self.cost2 * 500 * self.factor ** (level)).to_i
  end

  def get_crystal_cost_ratio(level, ratio)
    return get_crystal_cost(level).to_f * ratio
  end

  def get_fuel_cost(level)
    return (self.cost3 * 500 * self.factor ** (level)).to_i
  end

  def get_fuel_cost_ratio(level, ratio)
    return get_fuel_cost(level).to_f * ratio
  end

  def self.update_time(instance, format)
    science = instance.science
    durationInSeconds = instance.get_duration(instance.level)

    if(instance.start_time != nil)
      timeSinceResearch = (Time.now - instance.start_time).to_i
      restTime = durationInSeconds - timeSinceResearch

      if(restTime <= 0)
        instance.level = instance.level + 1
        instance.save
        instance.reset_build

        if not(format)
          return durationInSeconds;
        else
          return format_count_time(durationInSeconds)
        end
      else
        if not(format)
          return restTime;
        else
          return format_count_time(restTime)
        end
      end
    else
      if not(format)
        return durationInSeconds;
      else
        return format_count_time(durationInSeconds)
      end
    end
  end

end

app/controllers/sciences_controller.rb
class SciencesController < ApplicationController
  before_action :set_science, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /sciences
  # GET /sciences.json
  def index
    @sciences = Science.all
  end

  # GET /sciences/1
  # GET /sciences/1.json
  def show
  end

  # GET /sciences/new
  def new
    @science = Science.new
  end

  # GET /sciences/1/edit
  def edit
  end

  # POST /sciences
  # POST /sciences.json
  def create
    @science = Science.new(science_params)

    respond_to do |format|
      if @science.save
        format.html { redirect_to @science, notice: 'Science was successfully created.' }
        format.json { render :show, status: :created, location: @science }
      else
        format.html { render :new }
        format.json { render json: @science.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sciences/1
  # PATCH/PUT /sciences/1.json
  def update
    respond_to do |format|
      if @science.update(science_params)
        format.html { redirect_to @science, notice: 'Science was successfully updated.' }
        format.json { render :show, status: :ok, location: @science }
      else
        format.html { render :edit }
        format.json { render json: @science.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sciences/1
  # DELETE /sciences/1.json
  def destroy
    @science.destroy
    respond_to do |format|
      format.html { redirect_to sciences_url, notice: 'Science was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_science
      @science = Science.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def science_params
      params.require(:science).permit(:cost1, :cost2, :cost3, :factor, :duration, :condition, :name, :tier, :science_condition_id, :icon, :level_cap)
    end
end

app/helpers/sciences_helper.rb
module SciencesHelper
end

app/views/sciences/_form.html.erb
<%= form_for(@science) do |f| %>
  <% if @science.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@science.errors.count, "error") %> prohibited this science from being saved:</h2>

      <ul>
      <% @science.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :cost1 %><br>
    <%= f.number_field :cost1 %>
  </div>
  <div class="field">
    <%= f.label :cost2 %><br>
    <%= f.number_field :cost2 %>
  </div>
  <div class="field">
    <%= f.label :cost3 %><br>
    <%= f.number_field :cost3 %>
  </div>
  <div class="field">
    <%= f.label :factor %><br>
    <%= f.text_field :factor %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tier %><br>
    <%= f.text_field :tier %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :science_condition_id %><br>
    <%= f.number_field :science_condition_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sciences/edit.html.erb
<h1>Editing Science</h1>

<%= render 'form' %>

<%= link_to 'Show', @science %> |
<%= link_to 'Back', sciences_path %>

app/views/sciences/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert" style='color:red'><%= alert %></p>

<h1 class="userlabel">Forschung</h1>

<table id="table_sciences">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Metall</th>
      <th>Kristall</th>
      <th>Treibstoff</th>
      <th>Dauer</th>
      <th>Stufe</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.science_instances.sort_by{|instance| instance.science.science_condition_id}.each do |science_instance| %>
      <% inactive = nil %>
      <% if(!current_user.is_elsewhere_researching(science_instance)) %>
        <tr id="inactive">
        <% inactive = true %>
      <% else %>
        <tr id="active">
        <% inactive = false %>
      <% end %>

      <% if(science_instance.id) %>
        <% science = science_instance.science %>
        <td>
          <a>
            <img src= "<%= image_url("science_icons/" + science.icon)%>", width="50", height="50", id="icon">
          <span><%= Message.find_by_code(science.id).mes %></span></a>
        </td>
        <td><%= science.name %></td>
        <td><%= metal = science.get_metal_cost(science_instance.level) %></td>
        <td><%= crystal = science.get_crystal_cost(science_instance.level) %></td>
        <td><%= fuel = science.get_fuel_cost(science_instance.level) %></td>

        <% if(inactive) %>
          <td id = "not_running"><%= Science.update_time(science_instance, true).to_s %></td>
        <% else %>
          <td class="running"
              data-id="<%= science_instance.science_id %>"
              data-time="<%= Science.update_time(science_instance, false) %>"></td>
        <% end %>
        <% availability = current_user.can_research(science_instance)%>
        <td><%= science_instance.level %></td>

        <% if availability %>
          <td><%= button_to 'Forschen', research_science_instance_path(science_instance), method: :get %></td>
        <% end %>

        <% if(inactive && !availability) %>
          <td><a>Nicht verfügbar<span><%= science_instance.get_conditions() %></span></a></td>
        <% end %>
        <% if(!inactive) %>
          <td>
              <a>
                <%= button_to 'Abbrechen', cancel_research_science_instance_path(science_instance), method: :get %>
                <span><%= science_instance.get_refund %></span>
              </a>
            </td>
            <td>
              <%= button_to 'Sofort', instant_research_science_instance_path(science_instance), method: :get %>
            </td>
        <% end %>

      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/sciences/new.html.erb
<h1>New Science</h1>

<%= render 'form' %>

<%= link_to 'Back', sciences_path %>

app/views/sciences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost1:</strong>
  <%= @science.cost1 %>
</p>

<p>
  <strong>Cost2:</strong>
  <%= @science.cost2 %>
</p>

<p>
  <strong>Cost3:</strong>
  <%= @science.cost3 %>
</p>

<p>
  <strong>Factor:</strong>
  <%= @science.factor %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @science.duration %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @science.condition %>
</p>

<p>
  <strong>Name:</strong>
  <%= @science.name %>
</p>

<p>
  <strong>Tier:</strong>
  <%= @science.tier %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @science.icon %>
</p>

<p>
  <strong>ConditionID:</strong>
  <%= @science.science_condition_id %>
</p>

<%= link_to 'Edit', edit_science_path(@science) %> |
<%= link_to 'Back', sciences_path %>